../RTL/address_decoder.v
../RTL/BootRom_Wrapper/bootrom.v
../RTL/BootRom_Wrapper/Bootrom_wrapper.v
../RTL/BootRom_Wrapper/SRAM_CSR_logic.v
../RTL/core_addr_forward.v
../RTL/core_bootrom_remap.v
../RTL/core_intermediate.v
../RTL/CPU_SPI_WB_bridge.v
../RTL/global_defines.v
../RTL/gpio_display_logic.v
../RTL/picorv32.v
../RTL/qflexpress_subsystem/qflexpress_subsystem.v
../RTL/qflexpress_subsystem/qflexpress.v
../RTL/qflexpress_subsystem/magic_word_observability.v
../RTL/reset_synch.v
../RTL/soc_uart_subsystem/soc_uart_rx_input_synchronizer.v
../RTL/soc_uart_subsystem/soc_uart_subsystem.v
../RTL/soc_uart_subsystem/soc_uart_wishbone_signal_mapper.v
../RTL/soc_uart_subsystem/uart_top/uart_debug_if.v
../RTL/soc_uart_subsystem/uart_top/uart_defines.v
../RTL/soc_uart_subsystem/uart_top/uart_regs/raminfr.v
../RTL/soc_uart_subsystem/uart_top/uart_regs/uart_receiver/uart_receiver.v
../RTL/soc_uart_subsystem/uart_top/uart_regs/uart_receiver/uart_rfifo.v
../RTL/soc_uart_subsystem/uart_top/uart_regs/uart_regs.v
../RTL/soc_uart_subsystem/uart_top/uart_regs/uart_sync_flops.v
../RTL/soc_uart_subsystem/uart_top/uart_regs/uart_transmitter/uart_tfifo.v
../RTL/soc_uart_subsystem/uart_top/uart_regs/uart_transmitter/uart_transmitter.v
../RTL/soc_uart_subsystem/uart_top/uart_top.v
../RTL/soc_uart_subsystem/uart_top/uart_wb.v
../RTL/sram_bootrom_ready_logic.v
../RTL/SRAM_Controller/boot_controller.v
../RTL/SRAM_Controller/controller_path_mux.v
../RTL/SRAM_Controller/reset_controller.v
../RTL/SRAM_Controller/SRAM_controller.v
../RTL/SRAM_Controller/UART_Loader_Subsystem/UART_loader_subsystem.v
../RTL/SRAM_Controller/UART_Loader_Subsystem/UART_loader.v
../RTL/SRAM_Controller/UART_Loader_Subsystem/uart_rx_subsystem/byte_acc.v
../RTL/SRAM_Controller/UART_Loader_Subsystem/uart_rx_subsystem/uart_rx_fifo_wrapper/fifo/fifo_ctrl.sv
../RTL/SRAM_Controller/UART_Loader_Subsystem/uart_rx_subsystem/uart_rx_fifo_wrapper/fifo/fifo_mem.sv
../RTL/SRAM_Controller/UART_Loader_Subsystem/uart_rx_subsystem/uart_rx_fifo_wrapper/fifo/fifo.sv
../RTL/SRAM_Controller/UART_Loader_Subsystem/uart_rx_subsystem/uart_rx_fifo_wrapper/o_rts_logic.v
../RTL/SRAM_Controller/UART_Loader_Subsystem/uart_rx_subsystem/uart_rx_fifo_wrapper/uart_rx_fifo_wrapper.sv
../RTL/SRAM_Controller/UART_Loader_Subsystem/uart_rx_subsystem/uart_rx_fifo_wrapper/uart_rx.sv
../RTL/SRAM_Controller/UART_Loader_Subsystem/uart_rx_subsystem/uart_rx_subsystem.sv
../RTL/SRAM_Wrapper/SRAM_addr_virtualisation.v
../RTL/SRAM_Wrapper/SRAM_wrapper.v
../RTL/synchroniser.v
../RTL/system.v
